apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: "{{ .Release.Namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  ports:
    - name: tcp-postgresql
      nodePort: null
      port: 5432
      targetPort: tcp-postgresql
  selector:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  sessionAffinity: None
  type: ClusterIP