apiVersion: v1
kind: Secret
metadata:
  name: db-postgresql
  annotations:
    # needs to be created before DB
    argocd.argoproj.io/sync-wave: "-10"
stringData:
  postgres-password: postgres
  user-password: pass
  username: api