apiVersion: v1
kind: Service
metadata:
  name: todoapp-api
  labels:
    service: todoapp-api
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: todoapp
    tier: api