apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-demo-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chestercodes/argocd-demo-app-deploy.git
    targetRevision: HEAD
    path: chart
    helm:
      valueFiles:
      - values.yaml
      values: |
        image_tag: "{{ .Values.staging_image_tag }}"
        envname: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
